spring:
  datasource:
    url: jdbc:mysql://localhost:3306/docker
    username: docker
    password: docker
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    database: mysql
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace